Feature search for files
philippabele/developers-guide-to-linux pull request #10
Opened 2021-10-31 14:01 UTC by algern0p

Initiales write up, für locate und find command.

2021-11-01 11:01 UTC, philippabele commented on 01_basic_commands/020_search_files/search_files.md
> +Multiple approaches for searching for files are offered. If you are searching for a file by its file name `locate` is the choice, `find` is used to search for files by its attributes, `grep` allows s
Why are you mentioning grep? I did not find any explanation of the grep in the following sections.

2021-11-01 11:04 UTC, philippabele commented on 01_basic_commands/020_search_files/search_files.md
> +
Examples are great, but concrete tasks are better. Think of a are more interactive style of learning thinks. Prepare sample data by which the student has to do something on its own.

2021-11-01 11:08 UTC, philippabele commented on 01_basic_commands/020_search_files/search_files.md
> +## The `find` command
This document is far too long. Think of yourself learning new things. Wouldn't it be great to read something and immediately try it out on your own? Give the reader of your content smaller chunks. Split up this document into smaller parts.

2021-11-01 11:12 UTC, philippabele commented on 01_basic_commands/020_search_files/search_files.md
> +#### Predefined Actions
You don't have to reinvent the wheel. Give hints to the chapter in "The Linux command line", "--help" pages or the "man pages". Try not the repeat content which is already available there. Only give pointers what the student have to read. Focus yourself on simple practical exercises and a sample solution.

2021-11-01 11:16 UTC, philippabele requested changes
Great content, but we have to improve our working style to be more agile.

- split the content into smaller *.md files
- prepare sample practical exercises and explain what to do in theses *.md files
- prepare solutions for your exercises in *.sh files

Most import:

- commit earlier and more often
- I do not believe, that you wrote this document in just one sequence
- PR more often to get more feedback from me
- please let me know, if we have to speak with each other on the phone

2021-11-01 15:07 UTC, philippabele requested changes
We are almost there. The split files looks great and I had a lot of fun playing around with your exercises. Still there is some work to do:

- convert all files from CRLF to LF

By running `cat -A 021_solution.sh` it is apparent, that files are made in an Windows environment. Convert them to be useful in an Linux environment. [Hint1](https://stackoverflow.com/questions/14219092/bash-script-and-bin-bashm-bad-interpreter-no-such-file-or-directory) [Hint2](https://unix.stackexchange.com/questions/79702/how-to-test-whether-a-file-uses-crlf-or-lf-without-modifying-it)

Maybe you could add an git attributes to convert all CRLF line endings to LF. That would be the safest solution for further commits and PRs.

2021-11-02 08:58 UTC, algern0p commented
> We are almost there. The split files looks great and I had a lot of fun playing around with your exercises. Still there is some work to do:
> 
> * convert all files from CRLF to LF
> 
> By running `cat -A 021_solution.sh` it is apparent, that files are made in an Windows environment. Convert them to be useful in an Linux environment. [Hint1](https://stackoverflow.com/questions/14219092/bash-script-and-bin-bashm-bad-interpreter-no-such-file-or-directory) [Hint2](https://unix.stackexchange.com/questions/79702/how-to-test-whether-a-file-uses-crlf-or-lf-without-modifying-it)
> 
> Maybe you could add an git attributes to convert all CRLF line endings to LF. That would be the safest solution for further commits and PRs.

The files seem to be LF on my end, as they were created on a Linux environment. I cloned the repo into another location to see if git alters them, but they still seem to be LF.

2021-11-02 10:17 UTC, philippabele commented
Okay. It seems to be a Windows topic. I use WSL, cloned the git with cmd.exe `git clone ...` and run VS Code with `code .`

I changed my approach to start VS Code from inside WSL and all files work.

2021-11-02 10:19 UTC, merged