Feature cron
philippabele/developers-guide-to-linux pull request #65
Opened 2022-03-09 14:55 UTC by jehov4

Closes #63 and Closes #64

2022-04-02 18:56 UTC, philippabele requested changes

2022-04-02 18:56 UTC, philippabele commented on 02_operation_of_running_systems/060_schedule_tasks/061_schedule_tasks.md
> +This chapter is based of chapter 14.3 of Linux- Rheinwerk.
... is based on ...

2022-04-02 18:56 UTC, philippabele commented on 02_operation_of_running_systems/060_schedule_tasks/061_schedule_tasks.md
> +The crontab files are not to be edited directly, instead the tool `crontab` is used. The following flags are useful when working with the tool:
... file are not intended to be edited directly ...

2022-04-02 18:56 UTC, philippabele commented on 02_operation_of_running_systems/060_schedule_tasks/062_check_for_completion.md
> +An example taken from [here](https://bencane.com/2011/11/02/did-my-cronjob-run/) below:
please cite the important commands

2022-04-04 16:33 UTC, jehov4 commented on 02_operation_of_running_systems/060_schedule_tasks/061_schedule_tasks.md
> +This chapter is based of chapter 14.3 of Linux- Rheinwerk.
fixed

2022-04-04 16:33 UTC, jehov4 commented on 02_operation_of_running_systems/060_schedule_tasks/062_check_for_completion.md
> +An example taken from [here](https://bencane.com/2011/11/02/did-my-cronjob-run/) below:
added journalctl command call

2022-04-08 08:53 UTC, philippabele approved these changes

2022-04-08 08:53 UTC, merged